### ISSUE TITLE
Blank FASTA Headers  

### ISSUE THREAD

**Issue by eselimnl** [PU-SDS/DiMA#35]
The databases such as NCBI Virus may provides sequences which have not complete metadata. In this case, DiMA header decoding should fill the gaps with "Unknown" and keep the process going. 

Here is an example below: 
![image](https://user-images.githubusercontent.com/63191434/131333520-dabcd0a4-d5ac-40ab-98f3-7cd006d56cb9.png)

**Comment by ShanWeera** [comment]
> The databases such as NCBI Virus may provides sequences which have not complete metadata. In this case, DiMA header decoding should fill the gaps with "Unknown" and keep the process going.
> 
> Here is an example below:
> ![image](https://user-images.githubusercontent.com/63191434/131333520-dabcd0a4-d5ac-40ab-98f3-7cd006d56cb9.png)

Eyuub, fixing this would involve introducing an additional parameter (previously we have `no_decode_error`). This is because the default should always be to warn the user of something being wrong. If they would like us to handle the error, that's where they can use the extra parameter.

Do you have any suggestions for a parameter name?

**Comment by eselimnl** [comment]
How about `NA_replace` or `NA_decode` ?

**Comment by ShanWeera** [comment]
> How about `NA_replace` or `NA_decode` ?

Nice. That reminded me of `fillna` in pandas. The way it works is the user can decide what to fill with, like so `fillna("Unknown")`. We could take a similar approach, with the default being "Unknown". What do you think?

**Comment by eselimnl** [comment]
Makes sense. Agree.
